-- AlterTable
ALTER TABLE "Filter" ADD COLUMN     "isRanged" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "maxValue" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "minValue" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "possibleValue" DROP NOT NULL;
